server:
  #port: 8084
  port: ${server.peer2.port}

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://user:123456@peer1:8083/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
    fetch-registry: true
    register-with-eureka: true

security:
  basic:
    enabled: true
  user:
    name: user
    password: 123456
